{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggparallel
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggparallel_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggparallel/ggparallel_{{ version }}.tar.gz
  sha256: dc862e1e1b6d28aa14b9237d248fc71564a38efad4e4cafbb713de300ef090ba

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2 >=2.2.0
    - r-plyr >=1.8.4
    - r-reshape2 >=1.4.2
  run:
    - r-base
    - r-ggplot2 >=2.2.0
    - r-plyr >=1.8.4
    - r-reshape2 >=1.4.2

test:
  commands:
    - $R -e "library('ggparallel')"           # [not win]
    - "\"%R%\" -e \"library('ggparallel')\""  # [win]

about:
  home: http://github.com/heike/ggparallel
  license: MIT
  summary: Create hammock plots, parallel sets, and common angle plots with 'ggplot2'.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - djcomlab

# Package: ggparallel
# Version: 0.2.0
# Date: 2016-12-05
# Title: Variations of Parallel Coordinate Plots for Categorical Data
# Authors@R: c( person("Heike", "Hofmann", , "hofmann@mail.iastate.edu",c("aut", "cre")), person("Marie","Vendettuoli", role="aut") )
# Description: Create hammock plots, parallel sets, and common angle plots with 'ggplot2'.
# License: MIT + file LICENSE
# Depends: R (>= 2.10.0), ggplot2 (>= 2.2.0)
# Imports: reshape2 (>= 1.4.2), plyr (>= 1.8.4)
# Suggests: RColorBrewer
# URL: http://github.com/heike/ggparallel
# BugReports: https://github.com/heike/ggparallel/issues
# LazyData: true
# RoxygenNote: 5.0.1
# NeedsCompilation: no
# Packaged: 2016-12-05 14:16:24 UTC; heike
# Author: Heike Hofmann [aut, cre], Marie Vendettuoli [aut]
# Maintainer: Heike Hofmann <hofmann@mail.iastate.edu>
# Repository: CRAN
# Date/Publication: 2016-12-05 21:42:01
