travis:
  secure:
    BINSTAR_TOKEN: 2X7Q7RAKEC8kYg5ugNwByPd1pudKfL1aRHIbvxGxgUUKAEM4C3GH8N75JBW0JU2JJQLq9slMqGhgZBUUxFslWG/iVuuCZZuIgkmZK0DkoWW1KAimtnJvb/L5hhVwJbxzW/dL6o/v/LSOlRtN/UOHeCDfAHvcCpnx0yV1ZHB1h509Xz9KqGX5z3n9kk4fJ1/7GcwiPKyiTkcRoZ3VQTkY0hnF7PbVzFkCawXr36vflKjifQ3IHJnI+VBK+ojbNZzH9UErhAxNoJr+9Rag6AI7yBuLDJzB8GiTcDeHrMSJ+f28Y9sDF1bYA7PmahpusgVp5PdZSjW2zo5mj3+eNyVKcxi0uZGd1/XSSxiv/iiLFs2f+f4OW8xaBoyB/gWMRda5WCHAYFzAOOOHGVKj0PkQ+EfYKGBcT02PflNggvAS8L5mtSXgyPkZy3Iimk60iKldgTYZSXgZr6e9djGr2SoTMU9MmVzzNjTk9H+4+QGbW4cKieSvl8emrIPNSYWkP9M+QpdN7Hq05xKr/vOLhSVT9FYLU04H/n8lDyYvIRGFpOoTrBJv3doq7bDgYE1vAX8lCuFSp9Yj4A+AWmpZF43xHXeMR9iavOi1RdmgvVswrkAwSdrEuJRV5m9rsPeUI+xVoKTedmTMYAo87bGKaO/d7RYQIxB8hbXHEV1UytXyuNE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
