appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: xs9qf3Oe5ate3nq8TKyxGhK8CW0w0q0wNkpMF2e/OzX1YSp4nmrTKymUY+ZDq2vT65NmzJ5OA13ZO64EYwZn3dAEu+32Skq2uD7+C4xkwiZgKWXLNGXaixY8lQvjqUyV9pT10pFL+RN10PisY76hVRwd3un4f7HVQQ3AKUl2baYYrEuMo55qtnOlFjagjPDAS4bFY/x+W8rf1jlcxdUI4KqiaudvndnRdjnRp+YugZpT8/AzDQdkipQ3O/N55JzGnZ8TdEjn9KZ4J6DDsfzOemnM4oAADZfnf/qdClgUc2fFgSqW8rGm5P4gDd8X0iiXstVvrbdfVfUbwAO34nkFiu3fjHyrOu4KMa7r6Ocrh60zUZLyc8P+NDQmzPmk8tYHYPyb43xpS7VbsUwWMyIcQdR5MqhByJ1fvtgkal7ocAVpBotXIjwTro2Z9GjUNzoCqOVNHNj4vEZpa3gm1eNlSNt4ASDCSmnPRYoDsXdkL5mMgUW+Xie/yjFITndyKxAMJqHFLQb3Sl+3iI6JpAEjH46Hd0DTRigocdf81BPImfhcfqe9kSeulrIlxZT0ET7CUJlbuBhWq8vhhNVcuSUYg11Oz3+gO3SsrDrx+59ez0CiYKjb2eydNmXxU6Hj73p74XNE60VcrjlqBh8CXXHG3LiG0i9M6TtYzcYrZrRzijg=}
